export enum PupilsActionTypes {
  FETCH_ALL_PUPILS_REQUEST = "[pupils] FETCH_ALL_PUPILS_REQUEST",
  FETCH_ALL_PUPILS_SUCCESS = "[pupils] FETCH_ALL_PUPILS_SUCCESS",
  FETCH_ALL_PUPILS_ERROR = "[pupils] FETCH_ALL_PUPILS_ERROR",

  ADD_PUPIL_REQUEST = "[pupils] ADD_PUPIL_REQUEST",
  ADD_PUPIL_SUCCESS = "[pupils] ADD_PUPIL_SUCCESS",
  ADD_PUPIL_ERROR = "[pupils] ADD_PUPIL_ERROR",

  ADD_RESOURCE_REQUEST = "[pupils] ADD_RESOURCE_REQUEST",
  ADD_RESOURCE_SUCCESS = "[pupils] ADD_RESOURCE_SUCCESS",
  ADD_RESOURCE_ERROR = "[pupils] ADD_RESOURCE_ERROR",

  SUBTRACT_RESOURCE_REQUEST = "[pupils] SUBTRACT_RESOURCE_REQUEST",
  SUBTRACT_RESOURCE_SUCCESS = "[pupils] SUBTRACT_RESOURCE_SUCCESS",
  SUBTRACT_RESOURCE_ERROR = "[pupils] SUBTRACT_RESOURCE_ERROR",
}
